### PR TITLE
fixing anthropic call + add support for replicate and palm

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hey @elliottower, 

Noticed you had an old anthropic all (they updated their sdk a few days ago). Wanted to see if we could fix that and add support for some new LLM providers.  I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and wanted to help out.

Replaced the Anthropic raw endpoint call with a litellm `completions` call, this should ensure you're not impacted by any underlying changes. This call also adds support for new providers like Replicate, PaLM and a few you already support like Claude, Cohere, Azure, and OpenAI. 

The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.

Would love to know if this helps.

Happy to make any additional changes as required 😊

### CODE REVIEW

**Comment by krrishdholakia** [comment]
bump? @elliottower 

What is litellm missing to be useful to you? Any feedback here would be helpful.

**Comment by elliottower** [comment]
Hi Krish, I'm not the primary maintainer of this project, so I'm going to have to defer this to @yuxiang-wu

**Comment by elliottower** [comment]
As I said in the other issue I think it's best to add litellm as another backend similar to how LangChain was done https://github.com/Farama-Foundation/chatarena/pull/46, but if there are any other issues with this Anthropic backend class I'd be happy to accept a fix. I don't actually have an API key currently so can't test it myself unfortunately. In another PR I limited it to an earlier version of the python package pre-breaking changes, but if you wanted to update the code manually to the current Anthropic API and make a PR similar to this that'd be fine. Just don't want to add any more external libraries and keep this as light as possible

**Comment by elliottower** [comment]
Going to close this just for housekeeping but as I said above, let me know if things do not work with the restricted anthropic versions from #80, it should fix any issues this PR was solving (at the cost of potentially having less new features and some potential bugs which have been solved in new anthropic versions)

**Pull request closed without merging**
